---
name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install required packages
        run: sudo apt-get install -f yamllint shellcheck

      - name: Run shell check
        run: |
          shellcheck start.sh

      - name: Run yaml check
        run: |
          yamllint nginx-test.yaml
      
      - name: Run echo
        run: |
          echo "cicd ok ~~~~"
